### PR TITLE
Suggested edits to data

### PR DESCRIPTION
**Pull request by soyapark**
Hello there! I used Mavo to suggest the following edits:
I deleted my forked repo and did the same thing again from the beginning. Not sure if this will work.. I just want to fix this asap
Preview my changes here: http://haystack.csail.mit.edu/?storage=https%3A%2F%2Fgithub.com%2Fsoyapark%2Fwebsite-1%2Fdata%2Fpeople.json&people-storage=https%3A%2F%2Fgithub.com%2Fhaystack%2Fwebsite%2Fdata%2Fpeople.json

### CODE REVIEW

**Comment by soyapark** [comment]
well, the profile picture is still not displaying properly... 
image

**Comment by LeaVerou** [comment]
Yeah, I can see the problem. Feel free to do it manually since it's urgent, I added you as a collaborator!

**Comment by soyapark** [comment]
Thanks Lea! I edited the .json file directly for now because there are many problems at my profile (e.g. it goes to 404 page when my picture is clicked and my picture is broken etc)

**Comment by LeaVerou** [comment]
Hi @soyapark,

Now that you've edited your data so the urgency is out of the way, could you help me figure out what went wrong by answering a few questions? Looking at the edits, I don't see any changes to the image URLs, but I do see images uploaded. When you uploaded your image:

a) Did you see it being previewed? You mentioned something about a broken image?
b) Did the URL change to reflect the uploaded image?

Also, which browser/OS were you using?

Thanks!

**Comment by soyapark** [comment]
Sure! Happy to help.
a,b) as soon as I uploaded to my picture, my browser goes to the url I posted above, then the image was broken. 

I used macOS and Safari Version 11.1 (13605.1.33.1.2)

**Comment by LeaVerou** [comment]
Oooooh, I think I may know what's going on!
You have a *different* repo called `website`, and it's trying to read the image from there because it thinks it's the fork of this website!
When it created a fork of this repo, what was it called? Do you still have it in your profile?

**Comment by soyapark** [comment]
I think you are right! I have another repo named website which is for my personal website. 
When I forked this repo, the name was website-1: https://github.com/soyapark/website-1

**Comment by LeaVerou** [comment]
Fascinating. Yup, if I open the image URL and replace `website` with `website-1` it works!
So that should be relatively easy for me to fix in Mavo. 🤞

**Pull request closed without merging**
