### PR TITLE
Suggested edits to data

### PR DESCRIPTION
**Pull request by soyapark**
Hello there! I used Mavo to suggest the following edits:
I added my picture & website
Preview my changes here: http://haystack.csail.mit.edu/?storage=https%3A%2F%2Fraw.githubusercontent.com%2Fsoyapark%2Fwebsite-1%2Fmaster%2Fdata%2Fpeople.json&people-storage=https%3A%2F%2Fgithub.com%2Fhaystack%2Fwebsite%2Fdata%2Fpeople.json

### CODE REVIEW

**Comment by soyapark** [comment]
I tried to add the profile image several times but couldn't fix it! Can you help

**Comment by LeaVerou** [comment]
@soyapark why did you upload 3 images? What happened? Did it look like the upload failed?
Also looks like there's a bug and it keeps saving `"null"` when there's no value. Sigh.

**Comment by soyapark** [comment]
I uploaded three images since the editing interface was unclear. I thought I uploaded my image but it routes me to my own copy which I don't understand what that is. And at my own copy, it shows me my image is not uploaded. As a result, I repeated this procedure 3 times.  
Well as for my website, I tried to add my website instead of no value but it doesn't go through either.

**Comment by LeaVerou** [comment]
What do you mean "it routes me to my own copy"?

**Comment by soyapark** [comment]
image

**Comment by soyapark** [comment]
http://haystack.csail.mit.edu/?storage=https%3A%2F%2Fraw.githubusercontent.com%2Fsoyapark%2Fwebsite-1%2Fmaster%2Fimages%2Fpeople%2Fprofile.jpeg
as i upload my picture, it automatically goes to this url and mavo said there is error loading data.. 
I don't want to spend time fixing this anymore... should I just edit the .json file directly? 
My profile picture has been broken at the website for the past couple months (and I haven't changed the picture since I first update it)

**Pull request closed without merging**
